server:
  port: 8083

spring:
  application:
    name: order-service

  cloud:
    discovery:
      enabled: true
    # Optional: If using Config Server, make sure discovery is enabled after config is loaded

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
